---
- name: Ensure that the openssh packages are installed
  tags: openssh
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: openssh_yum
  with_items:
    - openssh
    - openssh-clients
    - openssh-server

- name: Attempting to overlay openssh client configurations
  tags: openssh
  become: true
  template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: 0644
  when: openssh_yum is success

- name: Attempting to overlay openssh server configurations
  tags: openssh
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  notify: restart sshd
  with_items:
    - { src: sshd_config.j2, dest: /etc/ssh/sshd_config, mode: '0600' }
    - { src: sshd.sysconfig.j2, dest: /etc/sysconfig/sshd, mode: '0640' }
  when: openssh_yum is success

- name: Ensure that sshd is started and enabled on boot
  tags: openssh
  become: true
  service:
    enabled: yes
    name: sshd
    state: started
  when: openssh_yum is success
...
