---
- name: Ensure that the openssh packages are installed
  tags: openssh
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: openssh_yum
  with_items:
    - openssh
    - openssh-clients
    - openssh-server

- block:
    - name: Execute openssh authentication task list
      import_tasks: openssh_auth.yml
      when:
        - openssh_auth is defined
        - openssh_auth|length > 0

    - name: Executing openssh client task list
      import_tasks: openssh_client.yml
      when:
        - openssh_client is defined
        - openssh_client|length > 0 

    - name: Executing openssh server task list
      import_tasks: openssh_server.yml
      when:
        - openssh_server is defined
        - openssh_server|length > 0
  tags: openssh
  become: true
  when: openssh_yum|success
...
